export const seedUsers = [
  { id: 1, name: 'Admin LampungWiFi', email: 'admin@lampungwifi.id', role: 'admin' },
  { id: 2, name: 'Rina Lestari', email: 'rina@example.com', role: 'member' },
  { id: 3, name: 'Adi Darmawan', email: 'adi@example.com', role: 'member' },
  { id: 4, name: 'Rizky Ramadhan', email: 'rizky@example.com', role: 'member' },
]

export const seedPlaces = [
  {
    id: 1,
    name: 'Kopi Janji Jiwa Kedaton',
    category: 'Cafe / Coffee Shop',
    address: 'Jl. Teuku Umar No.45, Kedaton, Bandar Lampung',
    district: 'Kedaton',
    latitude: -5.3839,
    longitude: 105.2604,
    wifi_available: true,
    wifi_access_type: 'Customer login',
    wifi_password: 'kopi-jjwa-2024',
    password_source: 'Verified by staff',
    access_notes: 'Ask cashier after ordering. Password rotated weekly.',
    wifi_speed_mbps: 48.2,
    upload_mbps: 12.5,
    ping_ms: 14,
    has_power_outlets: true,
    open_24_hours: false,
    quiet_zone: true,
    ambience_label: 'High Priority',
    map_context: 'Near Kedaton business strip, easy to reach from campus corridor.',
    operating_hours: 'Mon-Fri 08:00-22:00 | Sat 08:00-00:00 | Sun 09:00-21:00',
    image_tone: 'sunrise',
    submitter_name: 'Admin LampungWiFi',
    submitter_email: 'admin@lampungwifi.id',
    status: 'approved',
    created_at: '2026-05-01T08:30:00.000Z',
    updated_at: '2026-05-01T08:30:00.000Z',
  },
  {
    id: 2,
    name: 'Digital Hub Labuhan Ratu',
    category: 'Coworking Space',
    address: 'Near UIN Raden Intan Gate, Labuhan Ratu, Bandar Lampung',
    district: 'Labuhan Ratu',
    latitude: -5.3632,
    longitude: 105.2448,
    wifi_available: true,
    wifi_access_type: 'Free after front desk check-in',
    wifi_password: null,
    password_source: null,
    access_notes: 'Visitor receives same-day voucher after registering at front desk.',
    wifi_speed_mbps: 92.4,
    upload_mbps: 37.8,
    ping_ms: 9,
    has_power_outlets: true,
    open_24_hours: true,
    quiet_zone: true,
    ambience_label: 'Stable Ping',
    map_context: 'Popular remote-work stop for students and startup teams.',
    operating_hours: 'Open 24 hours',
    image_tone: 'lagoon',
    submitter_name: 'Admin LampungWiFi',
    submitter_email: 'admin@lampungwifi.id',
    status: 'approved',
    created_at: '2026-05-02T10:15:00.000Z',
    updated_at: '2026-05-02T10:15:00.000Z',
  },
  {
    id: 3,
    name: 'Gajah Mada Library',
    category: 'Library',
    address: 'Kedamaian District, Bandar Lampung',
    district: 'Kedamaian',
    latitude: -5.423,
    longitude: 105.271,
    wifi_available: true,
    wifi_access_type: 'Public WiFi',
    wifi_password: null,
    password_source: null,
    access_notes: 'Use open network and accept captive portal agreement.',
    wifi_speed_mbps: 36.5,
    upload_mbps: 18.1,
    ping_ms: 16,
    has_power_outlets: true,
    open_24_hours: false,
    quiet_zone: true,
    ambience_label: 'Quiet Zone',
    map_context: 'Good fallback for focused study and public meetings.',
    operating_hours: 'Mon-Sat 08:00-20:00 | Sun closed',
    image_tone: 'nightfall',
    submitter_name: 'Rina Lestari',
    submitter_email: 'rina@example.com',
    status: 'approved',
    created_at: '2026-05-03T07:45:00.000Z',
    updated_at: '2026-05-03T07:45:00.000Z',
  },
  {
    id: 4,
    name: 'Kopi Nuri Pahoman',
    category: 'Cafe / Coffee Shop',
    address: 'Jl. Way Lubuk No.1, Pahoman, Bandar Lampung',
    district: 'Pahoman',
    latitude: -5.4295,
    longitude: 105.2569,
    wifi_available: true,
    wifi_access_type: 'Free with purchase',
    wifi_password: 'nuri-fastlane',
    password_source: 'Printed on receipt',
    access_notes: 'Receipt code changes per purchase and expires in 8 hours.',
    wifi_speed_mbps: 101.3,
    upload_mbps: 44.2,
    ping_ms: 8,
    has_power_outlets: true,
    open_24_hours: false,
    quiet_zone: false,
    ambience_label: 'Work Hub',
    map_context: 'Busy but reliable. Best for short meetings and laptop work.',
    operating_hours: 'Daily 07:00-23:00',
    image_tone: 'earth',
    submitter_name: 'Adi Darmawan',
    submitter_email: 'adi@example.com',
    status: 'approved',
    created_at: '2026-05-04T12:20:00.000Z',
    updated_at: '2026-05-04T12:20:00.000Z',
  },
  {
    id: 5,
    name: 'WorkSpace Lampung',
    category: 'Coworking Space',
    address: 'Jl. ZA Pagar Alam No.88, Rajabasa, Bandar Lampung',
    district: 'Rajabasa',
    latitude: -5.3797,
    longitude: 105.2491,
    wifi_available: true,
    wifi_access_type: 'Paid day pass',
    wifi_password: null,
    password_source: null,
    access_notes: 'Staff provisions dedicated SSID after payment.',
    wifi_speed_mbps: 150.8,
    upload_mbps: 70.4,
    ping_ms: 6,
    has_power_outlets: true,
    open_24_hours: false,
    quiet_zone: true,
    ambience_label: 'Ultra Fast',
    map_context: 'Best raw speed in current directory. Quiet booths available.',
    operating_hours: 'Mon-Sat 08:00-22:00 | Sun 09:00-18:00',
    image_tone: 'tealglass',
    image_url: null,
    submitter_name: 'Admin LampungWiFi',
    submitter_email: 'admin@lampungwifi.id',
    status: 'approved',
    created_at: '2026-05-05T11:00:00.000Z',
    updated_at: '2026-05-05T11:00:00.000Z',
  },
  {
    id: 6,
    name: 'Mutun Bay Rest Stop',
    category: 'Rest Area',
    address: 'Jl. KH Ahmad Dahlan, Telukbetung Barat, Bandar Lampung',
    district: 'Telukbetung Barat',
    latitude: -5.5037,
    longitude: 105.2284,
    wifi_available: true,
    wifi_access_type: 'Open network',
    wifi_password: null,
    password_source: null,
    access_notes: 'Signal strongest near upper deck seating and ticket booth.',
    wifi_speed_mbps: 24.6,
    upload_mbps: 9.5,
    ping_ms: 21,
    has_power_outlets: false,
    open_24_hours: true,
    quiet_zone: false,
    ambience_label: 'Traveler Pick',
    map_context: 'Useful for travelers needing quick sync before ferry routes.',
    operating_hours: 'Open 24 hours',
    image_tone: 'coastal',
    submitter_name: 'Rizky Ramadhan',
    submitter_email: 'rizky@example.com',
    status: 'approved',
    created_at: '2026-05-05T17:40:00.000Z',
    updated_at: '2026-05-05T17:40:00.000Z',
  },
  {
    id: 7,
    name: 'Kopi Kenangan MBK',
    category: 'Cafe / Coffee Shop',
    address: 'Mall Boemi Kedaton, Bandar Lampung',
    district: 'Kedaton',
    latitude: -5.383,
    longitude: 105.2587,
    wifi_available: true,
    wifi_access_type: 'Customer login',
    wifi_password: null,
    password_source: null,
    access_notes: 'Contributor reports stable afternoon connection near window row.',
    wifi_speed_mbps: 46.5,
    upload_mbps: 15.8,
    ping_ms: 13,
    has_power_outlets: true,
    open_24_hours: false,
    quiet_zone: false,
    ambience_label: 'New Submission',
    map_context: 'Inside MBK south wing, close to cinema entrance.',
    operating_hours: 'Daily 10:00-22:00',
    image_tone: 'earth',
    submitter_name: 'Rizky Ramadhan',
    submitter_email: 'rizky@example.com',
    status: 'pending',
    created_at: '2026-05-09T09:10:00.000Z',
    updated_at: '2026-05-09T09:10:00.000Z',
  },
  {
    id: 8,
    name: 'Ruang Kreatif Darmajaya',
    category: 'Campus Lounge',
    address: 'Jl. ZA Pagar Alam No.93, Rajabasa, Bandar Lampung',
    district: 'Rajabasa',
    latitude: -5.3751,
    longitude: 105.2453,
    wifi_available: true,
    wifi_access_type: 'Student account',
    wifi_password: null,
    password_source: null,
    access_notes: 'Needs confirmation whether guest access works after 18:00.',
    wifi_speed_mbps: 32.1,
    upload_mbps: 18.2,
    ping_ms: 17,
    has_power_outlets: true,
    open_24_hours: false,
    quiet_zone: true,
    ambience_label: 'Under Review',
    map_context: 'Popular with student founders and project teams.',
    operating_hours: 'Mon-Sat 08:00-21:00',
    image_tone: 'lagoon',
    submitter_name: 'Rina Lestari',
    submitter_email: 'rina@example.com',
    status: 'pending',
    created_at: '2026-05-09T13:45:00.000Z',
    updated_at: '2026-05-09T13:45:00.000Z',
  },
  {
    id: 9,
    name: 'Sunset Deck Telukbetung',
    category: 'Restaurant',
    address: 'Jl. Yos Sudarso No.77, Telukbetung, Bandar Lampung',
    district: 'Telukbetung Selatan',
    latitude: -5.4488,
    longitude: 105.2661,
    wifi_available: true,
    wifi_access_type: 'Paid event package',
    wifi_password: null,
    password_source: null,
    access_notes: 'Original submission lacked proof that public guests can access WiFi.',
    wifi_speed_mbps: 18.4,
    upload_mbps: 7.2,
    ping_ms: 23,
    has_power_outlets: false,
    open_24_hours: false,
    quiet_zone: false,
    ambience_label: 'Needs Proof',
    map_context: 'Good ambience, weak evidence on public access.',
    operating_hours: 'Daily 16:00-23:00',
    image_tone: 'nightfall',
    submitter_name: 'Guest Reporter',
    submitter_email: 'guest@example.com',
    status: 'rejected',
    created_at: '2026-05-08T18:20:00.000Z',
    updated_at: '2026-05-10T08:20:00.000Z',
  },
]

export const seedReviews = [
  {
    id: 1,
    place_id: 1,
    author_name: 'Adi Darmawan',
    review_title: 'Stabil untuk kerja remote',
    rating_speed: 4,
    rating_comfort: 5,
    comment: 'Great place for remote work. WiFi stays consistent during peak hours and window seats have plenty of power sockets.',
    created_at: '2026-05-10T08:00:00.000Z',
  },
  {
    id: 2,
    place_id: 1,
    author_name: 'Rina Lestari',
    review_title: 'Upload aman buat meeting',
    rating_speed: 4,
    rating_comfort: 4,
    comment: 'Good upload speed for calls, but it gets slightly noisy after class hours. Morning sessions feel much calmer.',
    created_at: '2026-05-10T13:30:00.000Z',
  },
  {
    id: 3,
    place_id: 2,
    author_name: 'Fikri Maulana',
    review_title: 'Paling kencang dekat kampus',
    rating_speed: 5,
    rating_comfort: 5,
    comment: 'Fastest reliable place near campus belt. VPN, large file sync, and calls all worked without dropouts.',
    created_at: '2026-05-09T07:20:00.000Z',
  },
  {
    id: 4,
    place_id: 3,
    author_name: 'Nadia Putri',
    review_title: 'Nyaman buat riset panjang',
    rating_speed: 4,
    rating_comfort: 5,
    comment: 'Library network is stable enough for research work and public area stays quiet for long study blocks.',
    created_at: '2026-05-08T12:05:00.000Z',
  },
  {
    id: 5,
    place_id: 4,
    author_name: 'Bayu Saputra',
    review_title: 'Throughput tinggi, colokan cukup',
    rating_speed: 5,
    rating_comfort: 4,
    comment: 'Throughput is excellent. Best seat is near bar counter because outdoor tables share outlets with lights.',
    created_at: '2026-05-07T18:15:00.000Z',
  },
  {
    id: 6,
    place_id: 5,
    author_name: 'Salsa Rahma',
    review_title: 'Kecepatan paling kuat sejauh ini',
    rating_speed: 5,
    rating_comfort: 5,
    comment: 'Strongest speed in Bandar Lampung so far. Quiet booths and backup generator make it ideal for deadlines.',
    created_at: '2026-05-06T10:45:00.000Z',
  },
  {
    id: 7,
    place_id: 6,
    author_name: 'Arief Nugraha',
    review_title: 'Cukup untuk sinkron cepat',
    rating_speed: 3,
    rating_comfort: 3,
    comment: 'Useful for travel sync and map downloads, but seating is limited and power access is weak.',
    created_at: '2026-05-06T18:40:00.000Z',
  },
  {
    id: 8,
    place_id: 4,
    author_name: 'Lina Maharani',
    review_title: 'Koneksi stabil dua jam',
    rating_speed: 4,
    rating_comfort: 4,
    comment: 'Solid cafe for quick coworking sessions. Connection stayed steady through a two-hour design review call.',
    created_at: '2026-05-09T15:00:00.000Z',
  },
]
